FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apt-get update && apt-get install -y openssl

FROM base AS builder
RUN npm install -g turbo
WORKDIR /app
COPY . .
RUN turbo prune portal-web --docker

FROM base AS installer
WORKDIR /app
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install

COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
COPY tsconfig.base.json tsconfig.base.json
RUN pnpm turbo run db:generate
RUN pnpm turbo run build --filter=portal-web

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN groupadd --system --gid 1001 nodejs
RUN useradd --system --uid 1001 nextjs
USER nextjs

COPY --from=installer /app/apps/portal-web/next.config.ts .
COPY --from=installer /app/apps/portal-web/package.json .
COPY --from=installer --chown=nextjs:nodejs /app/apps/portal-web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/portal-web/.next/static ./apps/portal-web/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/apps/portal-web/public ./apps/portal-web/public

EXPOSE 3000
ENV PORT=3000

CMD ["node", "apps/portal-web/server.js"]
