FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN apt-get update && apt-get install -y openssl

FROM base AS builder
RUN npm install -g turbo
WORKDIR /app
COPY . .
RUN turbo prune admin-panel --docker

FROM base AS installer
WORKDIR /app
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install

COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
COPY tsconfig.base.json tsconfig.base.json
RUN pnpm turbo run db:generate
RUN pnpm turbo run build --filter=admin-panel

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN groupadd --system --gid 1001 nodejs
RUN useradd --system --uid 1001 nextjs
USER nextjs

COPY --from=installer /app/apps/admin-panel/next.config.ts .
COPY --from=installer /app/apps/admin-panel/package.json .
COPY --from=installer --chown=nextjs:nodejs /app/apps/admin-panel/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/admin-panel/.next/static ./apps/admin-panel/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/apps/admin-panel/public ./apps/admin-panel/public

EXPOSE 3000
ENV PORT=3000

CMD ["node", "apps/admin-panel/server.js"]
